### ISSUE TITLE
get ratelimit 

### ISSUE THREAD

**Issue by em7v** [TheLearneer/croyale#13]
Hi, it would be great. If there is an opportunity to get ratelimit. Here so for example. Where var ratetime is the client's object.
https://gist.github.com/Friday14/d7733cac6a8b2cba8ef0bc7a9a65a369

**Comment by bsantosh909** [comment]
Its implemented in the **Rewrite** branch _[WIP branch]_ with the commit 4da09ed

Only need to extremely test it now.
