### ISSUE TITLE
Implement caching

### ISSUE THREAD

**Issue by bsantosh909** [TheLearneer/croyale#14]
Implement caching so that unnecassary request wont be made to the API for the time being.

**Comment by Stitch07** [comment]
Add a map for your cache. When a request is made, set the tag, or name with all props. Clear the cache every 5 minutes?

I could PR this if needed.

**Comment by bsantosh909** [comment]
Its implemented in the **Rewrite** branch _[WIP branch]_ with the commit 4da09ed

Only need to extremely test it now.
