### ISSUE TITLE
Missing Endpoints

### ISSUE THREAD

**Issue by bsantosh909** [TheLearneer/croyale#16]
These are the functionality (_endpoints_) missing in the wrapper at current:

- [ ] Clan Search
- [ ] 1K tournaments
- [ ] In preparation tournaments
- [ ] Full tournaments
- [ ] Joinable tournaments
- [ ] Tournament search
- [ ] Popular decks

**Comment by BlackHoleFox** [comment]
FYI: The player verification endpoint was removed at Supercell's request by the API authors, so no reason to implement it now.

**Comment by bsantosh909** [comment]
@BlackHoleFox Removed from the list (**thanks**).
