### ISSUE TITLE
Error type inconsistencies

### ISSUE THREAD

**Issue by BlackHoleFox** [TheLearneer/croyale#3]
Offending line on: https://github.com/TheLearneer/croyale/blob/master/src/client.js line 85. 

When submitting a tag that is not registered to a player, it returns an error containing a 404 in a string. However, when submitting nothing it returns an error in a object type, which leads to impossibility in checking which it was on data returning.

**Comment by bsantosh909** [comment]
Should be gone with this update: https://github.com/TheLearneer/croyale/commit/8457cf0602c7b31fab954048a6857ebfab9418c9

_**Note:**_ Now every error message should be an **Error** object which should be cached using a `.catch()` block or a `try-catch` block.
