### ISSUE TITLE
Allowing Invalid Tags to be submitted leads to unusable error being returned

### ISSUE THREAD

**Issue by BlackHoleFox** [TheLearneer/croyale#4]
So the issue seems to be that the wrapper isnt catching invalid tags, leading to something returning an unintelligible mess that messes with other error checking logic. `TypeError: err.includes is not a function` is what shows up when I run a `getplayer` on `3333`

**Comment by bsantosh909** [comment]
Should be gone with this update: https://github.com/TheLearneer/croyale/commit/8457cf0602c7b31fab954048a6857ebfab9418c9
